### PR TITLE
Migrate to null safety and minor fixes

### PR DESCRIPTION
**Pull request by maeddin**
I haven't been able to test my changes yet because of other changes in Flutter 2.0.

### CODE REVIEW

**Comment by Saad29** [comment]
Really urgently needed pull request. Without this, it is hard to migrate to the latest firebase plugins. So would request the authors to please merge this pull request if everything is all right.

**Comment by maeddin** [comment]
I've since tested it and fixed another little bug I made. It should work now :)

**Comment by rymesaint** [comment]
waiting for this update

**Comment by maeddin** [comment]
> waiting for this update

What change are you waiting for?

**Comment by rymesaint** [comment]
> > waiting for this update
> 
> What change are you waiting for?

i needed null safety update, so my app can be updated to null safety but it stuck because dio firebase performance is not null safety

**Comment by dayron9110** [comment]
News?

**Pull request closed without merging**
