### PR TITLE
Update Firebase Performance to latest release

### PR DESCRIPTION
**Pull request by Zazo032**
`firebase_performance`'s last update is not compatible with the version used in this plugin

### CODE REVIEW

**Comment by danallen88** [comment]
Agreed, it would be great to get this updated so we can upgrade our Firebase Performance dependency.  However,[ 0.8.0 has breaking changes as noted here](https://pub.dev/packages/firebase_performance/changelog), so it's probably not as simple as just incrementing a version number.

**Comment by Zazo032** [comment]
I think the breaking changes don't affect this plugin's code

**Comment by Saifallak** [comment]
could you merge this please? @eyeem

**Comment by ndelanou** [comment]
@eyeem
This is preventing people to use the latest version of `firebase_performance`
Can you merge please ?

**Pull request closed without merging**
